

# This file was *autogenerated* from the file /home/crispo/Desktop/syst/syst_tb/galois_field/gen_mad.sage
from sage.all_cmdline import *   # import sage library

_sage_const_13 = Integer(13); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_16 = Integer(16)
import argparse, sys

parser = argparse.ArgumentParser(description='Generate GF(m) multiply and add.',
                formatter_class=argparse.ArgumentDefaultsHelpFormatter)
#parser.add_argument('-n, --num', dest='n', type=int, required=True,
#          help='number of coeffs')
parser.add_argument('-m', '--field', '-gf', '--gf', dest='gf', type=int, required=True, default=_sage_const_13 ,
          help='finite field (GF(2^m))')
parser.add_argument('--name', dest='name', type=str, default='GFE_mad',
          help = 'name for generated module; default: GFE_mad')
args = parser.parse_args()

K = GF(_sage_const_2 **args.gf, modulus="first_lexicographic", names=('a',)); (a,) = K._first_ngens(1)

def set_red(f, g):
  diff = len(f) - g[_sage_const_0 ] - _sage_const_1 

  while diff >= _sage_const_0 :
    s = f[-_sage_const_1 ]

    for i in g:
      f[diff + i] = s.symmetric_difference(f[diff + i])

    while len(f[-_sage_const_1 ]) == _sage_const_0 :
      del f[-_sage_const_1 ]

    diff = len(f) - g[_sage_const_0 ] - _sage_const_1 

  return f

f = []

for i in range(args.gf*_sage_const_2 ):
  f.append(set([i]))

f_red = set_red(f, K.modulus().exponents()[::-_sage_const_1 ])



mul = []
for i in range(args.gf*_sage_const_2 ):
  mul.append([])

for i in range(args.gf):
  for j in range(args.gf):
    mul[i+j].append("dinA[{0}]*dinB[{1}]".format(i,j))


fin = []
for i in range(args.gf):
  fin.append([])

for i, l in enumerate(f_red):
  for j in l:
    fin[i] += mul[j]


# verify
for i in range(_sage_const_16 ):
  ge = K.random_element()
  he = K.random_element()

  dinA = ge.polynomial()
  dinB = he.polynomial()
  
  tmp = _sage_const_0 

  for i, t in enumerate(fin):
    for j in t:
      tmp += a**i * eval(j)

  assert tmp == (ge*he)


print("""module {1} (
  input            clk,
  input  [{0} : 0] dinA,
  input  [{0} : 0] dinB,
  input  [{0} : 0] dinC,
  output [{0} : 0] dout
);\n""".format(args.gf-_sage_const_1 , args.name))

for i, l in enumerate(fin):
  print("  assign dout[{0}] = dinC[{0}] ^ ".format(i) + " ^ ".join([t.replace("*", "&") for t in l]) + ";")

print("\nendmodule\n")

